# Generated by Django 3.1.2 on 2022-05-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelookupevent',
            old_name='source',
            new_name='service',
        ),
    ]
